<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>簡易計算器</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f9;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .calculator {
            background-color: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
        }

        input {
            width: 260px;
            padding: 10px;
            margin-bottom: 10px;
            font-size: 24px;
            text-align: right;
            border: 1px solid #ddd;
            border-radius: 5px;
        }

        button {
            width: 60px;
            height: 60px;
            font-size: 24px;
            margin: 10px;
            border: none;
            border-radius: 5px;
            background-color: #4CAF50;
            color: white;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }

        .row {
            display: flex;
            justify-content: space-between;
        }
    </style>
</head>
<body>

<div class="calculator">
    <input type="text" id="display" disabled>
    
    <div class="row">
        <button onclick="appendNumber(7)">7</button>
        <button onclick="appendNumber(8)">8</button>
        <button onclick="appendNumber(9)">9</button>
        <button onclick="appendOperator('+')">+</button>
    </div>
    
    <div class="row">
        <button onclick="appendNumber(4)">4</button>
        <button onclick="appendNumber(5)">5</button>
        <button onclick="appendNumber(6)">6</button>
        <button onclick="appendOperator('-')">-</button>
    </div>
    
    <div class="row">
        <button onclick="appendNumber(1)">1</button>
        <button onclick="appendNumber(2)">2</button>
        <button onclick="appendNumber(3)">3</button>
        <button onclick="appendOperator('*')">*</button>
    </div>
    
    <div class="row">
        <button onclick="appendNumber(0)">0</button>
        <button onclick="clearDisplay()">C</button>
        <button onclick="calculateResult()">=</button>
        <button onclick="appendOperator('/')">/</button>
    </div>
</div>

<script>
    let display = document.getElementById("display");

    function appendNumber(number) {
        display.value += number;
    }

    function appendOperator(operator) {
        display.value += " " + operator + " ";
    }

    function clearDisplay() {
        display.value = "";
    }

    function calculateResult() {
        try {
            display.value = eval(display.value);
        } catch (error) {
            display.value = "錯誤";
        }
    }
</script>

</body>
</html>
